background {
    monitor =
    path = ~/Pictures/Wallpapers/gruvbox/ALLqk82.png
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33

    # Gruvbox colors
    outer_color = rgb(b8bb26)     # Gruvbox Green
    inner_color = rgb(282828)     # Gruvbox Dark Background
    font_color = rgb(ebdbb2)      # Gruvbox Foreground
    check_color = rgb(fabd2f)     # Gruvbox Yellow for checking
    fail_color = rgb(fb4934)      # Gruvbox Red for wrong password

    fade_on_empty = true
    placeholder_text = <i>Enter Password...</i> 
}
