theme = "gruvbox_custom"

[editor]
jump-label-alphabet = "jfkdls;aurieowpqnvmcxz"
line-number = "relative"
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
auto-signature-help = false

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = " "
nbsp = "␣"
tab = "»"
newline = "↲"
tabpad = "·"

[keys.normal]
"ret" = "goto_word" 
