[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
shebangs = ["python"]
roots = [".", "pyproject.toml", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["pyright"]
indent = { tab-width = 4, unit = "    " }
auto-format = true

[language.formatter]
command = "black"
args = [
  "-",
  "--quiet",
  "--line-length=80"
]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
reportMissingTypeStubs = true

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true
