[window]
decorations = "None"

[scrolling]
history = 0

# Font configuration
[font]
normal = { family = "JetBrainsMonoNerdFont", style = "Regular" }
size = 10.0


[keyboard]
bindings = [
  { key = "V", mods = "Alt", action = "Paste" },
  { key = "C", mods = "Alt", action = "Copy" },
]

# Base16 Gruvbox dark, hard 256 - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
[colors.primary]
background = '#202020'
foreground = '#d5c4a1'

[colors.cursor]
text = '#1d2021'
cursor = '#d5c4a1'

[colors.normal]
black = '#1d2021'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white ='#d5c4a1'

[colors.bright]
black = '#665c54'
red = '#fe8019'
green = '#3c3836'
yellow = '#504945'
blue = '#bdae93'
magenta = '#ebdbb2'
cyan = '#d65d0e'
white = '#fbf1c7'

[colors]
draw_bold_text_with_bright_colors = false
indexed_colors = [
    { index = 16, color = '#fe8019' },
    { index = 17, color = '#d65d0e' },
    { index = 18, color = '#3c3836' },
    { index = 19, color = '#504945' },
    { index = 20, color = '#bdae93' },
    { index = 21, color = '#ebdbb2' },
]
