[notebook]
dir = "~/org/zet"

[tool]
editor = "nvim"
pager = "less -FIRX"
fzf-preview = "bat -p --color always {-1}"

[alias]
main = 'zk edit -m "main"'
todos = 'zk edit -m "todo"'

[extra]
author = "R3ZV"
